# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import estoque_pb2 as estoque__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in estoque_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EstoqueStub(object):
    """Serviço do estoque
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdicionarCarro = channel.unary_unary(
                '/estoque.Estoque/AdicionarCarro',
                request_serializer=estoque__pb2.Carro.SerializeToString,
                response_deserializer=estoque__pb2.Resposta.FromString,
                _registered_method=True)
        self.RemoverCarro = channel.unary_unary(
                '/estoque.Estoque/RemoverCarro',
                request_serializer=estoque__pb2.RemoverRequest.SerializeToString,
                response_deserializer=estoque__pb2.Resposta.FromString,
                _registered_method=True)
        self.ListarCarros = channel.unary_stream(
                '/estoque.Estoque/ListarCarros',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=estoque__pb2.Carro.FromString,
                _registered_method=True)


class EstoqueServicer(object):
    """Serviço do estoque
    """

    def AdicionarCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarCarros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstoqueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdicionarCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarCarro,
                    request_deserializer=estoque__pb2.Carro.FromString,
                    response_serializer=estoque__pb2.Resposta.SerializeToString,
            ),
            'RemoverCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverCarro,
                    request_deserializer=estoque__pb2.RemoverRequest.FromString,
                    response_serializer=estoque__pb2.Resposta.SerializeToString,
            ),
            'ListarCarros': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarCarros,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=estoque__pb2.Carro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estoque.Estoque', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estoque.Estoque', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Estoque(object):
    """Serviço do estoque
    """

    @staticmethod
    def AdicionarCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.Estoque/AdicionarCarro',
            estoque__pb2.Carro.SerializeToString,
            estoque__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.Estoque/RemoverCarro',
            estoque__pb2.RemoverRequest.SerializeToString,
            estoque__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarCarros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/estoque.Estoque/ListarCarros',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            estoque__pb2.Carro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
